server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: wjl1237107
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.wjl.model
  mapper-locations: classpath:/mybatis/*.xml

logging:
  file:
    name: log/log.log
  level:
    root: info
    jiuqi: debug

